<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.silverwing</groupId>
        <artifactId>sw-logistics-platform</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>silverwing-ops-service</artifactId>
    <packaging>pom</packaging>
    <name>Operations and Maintenance Service</name>
    <description>Device health management, work order management, predictive maintenance</description>

    <modules>
        <module>silverwing-ops-service-domain</module>
        <module>silverwing-ops-service-dbsdk</module>
        <module>silverwing-ops-service-infrastructure</module>
        <module>silverwing-ops-service-client</module>
        <module>silverwing-ops-service-app</module>
        <module>silverwing-ops-service-adapter</module>
        <module>silverwing-ops-service-start</module>
    </modules>
</project>
