spring:
  config:
    import:
      - nacos:common-redis.yml
      - nacos:common-sa-token.yml
      - nacos:silverwing-gateway.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:b7273740-ffae-4c91-9e78-ba1360e42a0e}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
      config:
        server-addr: ${NACOS_SERVER_ADDR:nacos:8848}
        namespace: ${NACOS_NAMESPACE:b7273740-ffae-4c91-9e78-ba1360e42a0e}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
